services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - blackjack-engine-backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10

  blackjack-engine:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/coreymerritt/blackjack-engine:1.0.0
    image: blackjack-engine:local
    container_name: blackjack-engine
    ports:
      - "1080:8000"
    env_file:
      - .env
    networks:
      - blackjack-engine-backend
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:

networks:
  blackjack-engine-backend:
    driver: bridge
