from enum import Enum

class GameState(Enum):
  NOT_STARTED = 0
  BETTING = 1
  DEALING = 2
  INSURANCE = 3
  EARLY_SURRENDER = 4
  DEALER_BLACKJACK_CHECK = 5
  LATE_SURRENDER = 6
  HUMAN_PLAYER_DECISIONS = 7
  AI_PLAYER_DECISIONS = 8
  DEALER_DECISIONS = 9
  PAYOUTS = 10
  CLEANUP = 11
