from enum import Enum


class GameState(Enum):
  NOT_STARTED = 0
  BETTING = 1
  DEALING = 2
  PLAYER_BLACKJACK_CHECK = 3
  INSURANCE = 4
  EARLY_SURRENDER = 5
  DEALER_BLACKJACK_CHECK = 6
  LATE_SURRENDER = 7
  HUMAN_PLAYER_DECISIONS = 8
  AI_PLAYER_DECISIONS = 9
  DEALER_DECISIONS = 10
  RESULTS = 11
  PAYOUTS = 12
  CLEANUP = 13
